dir=/media/sda1/Shared/aria2
continue=true
input-file=/var/lib/aria2/aria2.session
save-session=/var/lib/aria2/aria2.session
save-session-interval=60
file-allocation=trunc
max-concurrent-downloads=5
split=5
bt-save-metadata=true
enable-dht=true
bt-enable-lpd=true
listen-port=6881
dht-listen-port=6881
seed-ratio=0.0001
seed-time=1
max-overall-upload-limit=1
max-upload-limit=1
enable-rpc=true
rpc-listen-port=6800
rpc-secret=9bvE3UDXJF82QANjHhNB
rpc-listen-all=false
rpc-allow-origin-all=true
bt-tracker=udp://tracker.opentrackr.org:1337/announce,udp://open.demonii.com:1337/announce,udp://open.stealth.si:80/announce,udp://wepzone.net:6969/announce,udp://udp.tracker.projectk.org:23333/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.theoks.net:6969/announce,udp://tracker.srv00.com:6969/announce,udp://tracker.qu.ax:6969/announce,udp://tracker.plx.im:6969/announce,udp://tracker.gmi.gd:6969/announce,udp://tracker.fnix.net:6969/announce,udp://tracker.dler.org:6969/announce,udp://tracker.004430.xyz:1337/announce,udp://tracker-udp.gbitt.info:80/announce,udp://torrents.tmtime.dev:6969/announce,udp://t.overflow.biz:6969/announce,udp://martin-gebhardt.eu:25/announce,udp://ipv4announce.sktorrent.eu:6969/announce,udp://evan.im:6969/announce
