server:
    interface: 127.0.0.1
    interface: ::1
    port: 5353
    do-ip4: yes
    do-ip6: yes
    do-udp: yes
    do-tcp: yes
    access-control: 127.0.0.0/8 allow
    access-control: ::1 allow
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"
    hide-identity: yes
    hide-version: yes
    qname-minimisation: yes
    aggressive-nsec: yes
    prefetch: no
    minimal-responses: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes
    do-not-query-localhost: no

forward-zone:
    name: "."
    forward-tls-upstream: no
    forward-addr: 127.0.2.1@53

# router-config.blocklists.enable: yes
# router-config.blocklists.url: https://small.oisd.nl/domainswild
# router-config.blocklists.url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
# router-config.blocklists.return-nxdomain: yes
include: "/etc/unbound/unbound.conf.d/router-config-blocklist.conf"
