# route-config: ipv6-mode=server

interface=br0
bind-interfaces

port=53
no-resolv
no-hosts
server=127.0.0.1#5353

dhcp-range=172.16.0.100,172.16.0.250,12h
dhcp-option=3,172.16.0.1
dhcp-option=6,172.16.0.1

enable-ra
dhcp-range=::,constructor:br0,ra-stateless,64
dhcp-option=option6:dns-server,[fd00:16::1]

log-dhcp
