# Wi-Fi network: 5 GHz on wlp1s0_5g
interface=wlp1s0_5g
driver=nl80211
bridge=br0
ssid=HG-CAT-5G
hw_mode=a
country_code=JP
country3=0x4f
ieee80211d=1
ieee80211h=1
channel=100
ignore_broadcast_ssid=1
wpa=2
wpa_key_mgmt=SAE
wpa_passphrase=hackinggate
rsn_pairwise=CCMP
ieee80211w=2
ieee80211ax=1
ieee80211n=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]
ieee80211ac=1
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=106
he_oper_chwidth=1
he_oper_centr_freq_seg0_idx=106
multicast_to_unicast=1
sae_pwe=2
